[package]
name = "duckdb-server-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb = "0.10.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
